import { Kind } from '../enums';
import { UserShort } from './user';

export interface Track {
  id: number;
  kind: Kind.Track;
  created_at: string;
  last_modified: string;
  permalink: string;
  permalink_url: string;
  title: string;
  duration: number;
  sharing: string;
  waveform_url: string;
  stream_url: string;
  uri: string;
  user_id: number;
  artwork_url: string;
  comment_count: number;
  commentable: boolean;
  description: null | string;
  download_count: number;
  downloadable: boolean;
  embeddable_by: string;
  favoritings_count: number;
  genre: string;
  isrc: string | null;
  label_id: number | null;
  label_name: null | string;
  license: string;
  original_content_size: number;
  original_format: string;
  playback_count: number;
  purchase_title: null | string;
  purchase_url: null | string;
  release: string;
  release_day: number | null;
  release_month: number | null;
  release_year: number | null;
  reposts_count: number;
  state: string;
  streamable: boolean;
  tag_list: string;
  track_type: null | string;
  user: UserShort;
  likes_count: number;
  bpm: null;
  key_signature: string;
  user_favorite: boolean;
  user_playback_count: null;
  video_url: null | string;
  download_url: null | string;
}
